### ISSUE TITLE
запись в слот, который кто то уже занял после загрузки страницы

### ISSUE THREAD

**Issue by dermanov-ru** [levenwadim/vklinike#9]
трейс
- зашел на страницу, пользователь А
- вижу слоты на день Х
- зашел в инконито на эту же страницу, пользователь Б
- Б записался там на 9 утра
- А пробует записаться на это время (буду все так же на свой странице, ничего не обновляя)
- А успешно записался в занятый слот

**Comment by levenwadim** [comment]
Здесь вопрос, после добавления этих записей они отменялись? Т.к сейчас в базе нет "дублирующих" записей к одному врачу на одно и то же время [screenshot](https://drive.google.com/file/d/1jtSM2jQ7_2zg4GuVMF3LqeDbJRcX4lNt/view?usp=sharing)

Так же повторил трейс и запись произвести сайт не дал (код не менял, ну и этот момент тестировал во время разработки, так же запись не проходила) [screenshot](https://drive.google.com/file/d/1nnCC1WRd073Ym4P6EIFTf2seg8OKoIsc/view?usp=sharing)

Пожалуйста, проверьте еще раз)

**Comment by dermanov-ru** [comment]
ошибку повторить не удалось)
возможно, я что-то сделал не так в первый раз.
